# Generated by Django 4.2.3 on 2024-05-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
