# Generated by Django 4.2.3 on 2024-07-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_message_room_remove_conversationmessage_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='caption',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ALUMNO', 'Alumno'), ('PROFESOR', 'Profesor'), ('ADMIN', 'Admin')], default='ALUMNO', max_length=25),
        ),
    ]
