# Generated by Django 4.2.3 on 2024-08-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.CharField(default='', max_length=255),
        ),
    ]
