# Generated by Django 4.2.3 on 2024-08-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.CharField(default='', max_length=255),
        ),
    ]
