# Generated by Django 4.2.3 on 2024-08-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_room_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
