# Generated by Django 4.2.3 on 2024-08-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_user_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='client',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='url',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
