# Generated by Django 4.2.3 on 2024-08-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_client_room_name_remove_room_url_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
