# Generated by Django 4.2.3 on 2024-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_room_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('grupos', 'Grupos'), ('mensajes', 'Mensajes')], default='mensajes', max_length=255),
        ),
    ]
